#!/command/with-contenv bash

export NOVNC_LISTEN_PORT=8080
export VNC_LISTEN_PORT=5900
exec /usr/bin/novnc_server --listen ${NOVNC_LISTEN_PORT} --vnc localhost:${VNC_LISTEN_PORT} --web /var/www > /dev/null 2>&1
